### PR TITLE
Add localaxes to beams

### PR DESCRIPTION
**Pull request by jginternational**
This implements #103 

Please @RiccardoRossi try to create a line, assign a Small displacements beam, mesh and write. See the mdpa file

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
There is no mdpa file in your changed files

**Comment by jginternational** [comment]
@pooyan-dadvand I mean, try to do an example and run it. Check the generated mdpa

**Comment by jginternational** [comment]
@pooyan-dadvand I mean, try to do an example and run it. Check the generated mdpa

**Comment by philbucher** [comment]
hi @RiccardoRossi, good to have you back :)
I will pass the ball further to @KlausBSautter, he is the expert

**Comment by KlausBSautter** [comment]
Hi i tried to work with the add-localaxes-to-beams branch but dont succeed. With the master branch I can run a problem but as soon as I work an this new branch I get an empty *.mdpa file. Is there anything special I have to take care of?

**Comment by jginternational** [comment]
It is working on my side. Look at this

[testt.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/1341214/testt.gid.zip)


@KlausBSautter

**Comment by KlausBSautter** [comment]
Hey @jginternational thanks for providing that example, I see the Local_AXIS_2 entry in the *.mdpa file which looks good. Nevertheless I cant run that example as I apparently have no LOCAL_AXIS_2 as a variable ?? I am using the current version of the KRATOS master branch.

**Comment by jginternational** [comment]
@KlausBSautter I think that @RiccardoRossi has the answer to that

**Comment by pooyan-dadvand** [comment]
ping @RiccardoRossi

**Pull request merged**
