### PR TITLE
remove lists of SMPs for ComputingModelPart

### PR DESCRIPTION
**Pull request by philbucher**
in order to use the default of the solver
=> see https://github.com/KratosMultiphysics/Kratos/pull/4978 (already merged)

### CODE REVIEW

**Comment by philbucher** [comment]
@jginternational I tried to replace the model-part name for the output from `Structure.computing_domain` to `Structure` by removing a setting (see second commit), but it then writes `Structure.` and I don't know how to get rid of the "."
Can you please have a look?
Thanks

**Comment by philbucher** [comment]
ping @jginternational

**Comment by jginternational** [comment]
Hi @philbucher 
I'm experiencing some stange behaviour with github notifications.

This should be easy to fix

**Comment by jginternational** [comment]
@philbucher you can test it

**Comment by philbucher** [comment]
works, thx @jginternational

**Pull request merged**
