### PR TITLE
[MPM] New gid interface for MPM

### PR DESCRIPTION
**Pull request by bodhinandach**
Hi @jginternational this is the PR and separate branch which I mentioned to you earlier.
This is done following the new PR https://github.com/KratosMultiphysics/Kratos/pull/3059 in the other branch. 

I just made some modifications of the old 'MainKratos.py' file and named it 'KratosParticle.py'. Please check the commits I made.

As for the 'ProjectParameters.json', please find attached are the old and new ProjectParameter files that I would like to modify. I changed the format to .txt as github cant support json.
[ProjectParameters (new).txt](https://github.com/KratosMultiphysics/GiDInterface/files/2483317/ProjectParameters.new.txt)
[ProjectParameters (old).txt](https://github.com/KratosMultiphysics/GiDInterface/files/2483311/ProjectParameters.old.txt)

I will write in the comments of what I want to change specifically. 
I really appreciate if you could help me with that. Many thanks, Javi.

### CODE REVIEW

**Comment by bodhinandach** [comment]
Things to change:

- Please change `"model_part_name"`, `"domain_size"`, and `"time_step"` from `"problem_data"` to `"solver_settings"`.


- Please group all the process lists: `"constraints_process_list", "loads_process_list", "list_other_processes",` and `"gravity"` to a group of parameter name "**processes**". This is the same as in StructuralMechanicsApplication.
- For all the processes specified there **except "gravity"**, the `"Parameters"["model_part_name"]` should contain `"Background_Grid"` in front of the actual model_part_name. e.g., if the actual name is "`DISPLACEMENT_Displacement_Auto1`", or "`LOAD_Load_Auto_1`", the expected output should be "**Background_Grid.DISPLACEMENT_Displacement_Auto1**" and "**Background_Grid.LOAD_Load_Auto_1**", respectively. 
- The `"gravity"["Parameter"]["model_part_name"]` should always refer to "**MPM_Material**" as what it is now.


- The "`body_output_configuration`" and "`grid_output_configuration`" should be changed to "**body_output_process**" and "**grid_output_process**", respectively.
- Then both of them need to be grouped as "**output_processes**" group.
- Then, the "`python_module`", "`kratos_module`", "`process_name`", and "`Parameters`" are also need to be added. The configuration for "**body_output_process**" are always the same, i.e:
```
"body_output_process" : [{
            "python_module" : "mpm_gid_output_process",
            "kratos_module" : "KratosMultiphysics.ParticleMechanicsApplication",
            "process_name"  : "ParticleMPMGiDOutputProcess",
            "Parameters"    : {
                "model_part_name"           : "MPM_Material",
                "output_name"               : problem_name + "_Body",
                "postprocess_parameters"    : {...}
}]
```
while the "grid_output_process" is also always the same:
```
"grid_output_process" : [{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "Parameters"    : {
                "model_part_name"           : "Background_Grid",
                "output_name"               : problem_name + "_Grid",
                "postprocess_parameters"    : {...}
}]
```

**Comment by bodhinandach** [comment]
@jginternational I modified the request above after merging the new model v3. Please find the (NOT NEEDED ANYMORE) section.

**Comment by bodhinandach** [comment]
@jginternational Just to let you know, I updated the new KratosParticle.py. Also, I want to add the following option in the interface as well as in the "`solver_settings`" if possible:
```
        "time_integration_method"      : "implicit",
        "scheme_type"                        : "newmark",
```
The application might become larger and include so many different scheme and time integration method, so we decided to write it in the ProjectParameters as well. I am not sure whether the StructuralMechanics have similar stuffs or not.

**Comment by jginternational** [comment]
I've detected a bigger error in GiD, so I've stopped this development

**Comment by jginternational** [comment]
Looks good

**Comment by bodhinandach** [comment]
@jginternational please confirm one more time. This works for me.

**Comment by bodhinandach** [comment]
@jginternational should I merge this?

**Comment by jginternational** [comment]
In a static case, it tries to find the time integration.

```
Traceback (most recent call last):
  File "MainKratos.py", line 19, in <module>
    simulation = ParticleMechanicsAnalysis(model,parameters)
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\ParticleMechanicsApplication\python_scripts\particle_mechanics_analysis.py", line 67, in __init__
    super(ParticleMechanicsAnalysis, self).__init__(model, project_parameters)
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 41, in __init__
    self._GetSolver().AddVariables() # this creates the solver and adds the variables
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 190, in _GetSolver
    self._solver = self._CreateSolver()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\ParticleMechanicsApplication\python_scripts\particle_mechanics_analysis.py", line 93, in _CreateSolver
    return python_solvers_wrapper_particle.CreateSolver(self.model, self.project_parameters)
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\ParticleMechanicsApplication\python_scripts\python_solvers_wrapper_particle.py", line 23, in CreateSolver
    time_integration_method = custom_settings["solver_settings"]["time_integration_method"].GetString()
RuntimeError: Error: --------- ERROR : --------- getting a value that does not exist. entry string : time_integration_method
```

**Comment by bodhinandach** [comment]
That was the case before. I fixed it and merged the modification recently. See https://github.com/KratosMultiphysics/Kratos/pull/3155

**Pull request merged**
