### PR TITLE
Structural interface strategies bugfix

### PR DESCRIPTION
**Pull request by rubenzorrilla**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Before merge @rubenzorrilla can you put the new main script in the StructuralMechanicsApplication?

**Comment by rubenzorrilla** [comment]
@loumalouomega sure! Is it ok if I delete the old one?

**Comment by loumalouomega** [comment]
The idea is to replace it

**Comment by rubenzorrilla** [comment]
Done! :metal:

**Pull request merged**
