### PR TITLE
Update the old names of deprecated conditions

### PR DESCRIPTION
**Pull request by loumalouomega**
Fortunately the number of deprecated conditions in the GUI was very limited

Related https://github.com/KratosMultiphysics/Kratos/pull/6475

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Both applications have examples. Have you tested them?

**Comment by loumalouomega** [comment]
> 
> 
> Both applications have examples. Have you tested them?

I assume the changes will continue working, we are just changing names

**Comment by rubenzorrilla** [comment]
I've just tried both and it works.

**Comment by jginternational** [comment]
How proud I am of you two! @loumalouomega @rubenzorrilla 
Even when there is no changes in tcl, is always glad to see you in this repo

**Pull request merged**
