### PR TITLE
Add time parameters with substepping for structural

### PR DESCRIPTION
**Pull request by jginternational**
Implements KratosMultiphysics/Kratos#4509

Looks like this
image

### CODE REVIEW

**Comment by jginternational** [comment]
It's ProjectParameters.json looks like:

```json
"solver_settings"  : {
        "time_stepping"                      : {
            "time_step_intervals" : {
                "Delta time interval 1" : {
                    "interval"  : [0.0,0.5],
                    "time_step" : 0.1
                },
                "Delta time interval 2" : {
                    "interval"  : [0.5,"End"],
                    "time_step" : 0.02
                }
            }
        },
        "solver_type"                        : "Dynamic",
        "model_part_name"                    : "Structure",
        "domain_size"                        : 3
}
```

**Comment by jginternational** [comment]
I know it! This is the implementation required once KratosMultiphysics/Kratos#4509 is merged, just to show a possible result

**Review by philbucher — APPROVED** [review]
sorry I didn't realize I was still blocking

if you tested it then it is ok for me :)

**Comment by jginternational** [comment]
I'm about to merge this branch.
It works on Structural app only but the code is common, so any other app can use it in the future.

Currently working this way
image

If theres nothing wrong @KratosMultiphysics/structural-mechanics I'll merge it soon

**Comment by jginternational** [comment]
> sorry I didn't realize I was still blocking
> 
> if you tested it then it is ok for me :)

I forgot about this PR. I'm trying to clean the PR list 🤕

**Comment by AlejandroCornejo** [comment]
yuhu!!!

**Pull request merged**
