### PR TITLE
Adding new reservoir temperature condition

### PR DESCRIPTION
**Pull request by lorenzogracia**

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Lorenzo is back! /play danielsan

**Comment by jginternational** [comment]
Just a remind, @lorenzogracia @rubenzorrilla Everything here must have compatibility with the Release

**Comment by rubenzorrilla** [comment]
Not my app. I was just pinging you @jginternational

**Comment by lorenzogracia** [comment]
Hi @jginternational, yes!! I am checking everything for release version!! Thanks for the reminder!

**Comment by jginternational** [comment]
Welcome back @lorenzogracia !

**Pull request merged**
