### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by jginternational**
@KratosMultiphysics/technical-committee 

Copied from https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/license.txt

Should I add an author name?

### CODE REVIEW

**Comment by roigcarlo** [comment]
Weren't we using Bsd-4?

**Comment by philbucher** [comment]
I thought so too

**Comment by RiccardoRossi** [comment]
yes we are using the 4-clause ...please keep using that

**Comment by jginternational** [comment]
So, better this way

**Comment by pooyan-dadvand** [comment]
I agree

**Pull request merged**
