### PR TITLE
making membrane avaiable in release mode

### PR DESCRIPTION
**Pull request by philbucher**
please test it @RiccardoRossi

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@playpaolo

**Comment by playpaolo** [comment]
tried an example of a membrane exposed to a constant inner pressure. It works (see video attached)

**Comment by philbucher** [comment]
I dont see the video :/

Can you approve then please?

**Comment by playpaolo** [comment]
I dont kno why its not getting uploaded. Any idea? Its around 5 Mb

**Comment by playpaolo** [comment]
I dont know what the files dont get uploaded. Neither video, nor a picture. Any idea?

**Comment by RiccardoRossi** [comment]
@philbucher this does not need approval in this repo (and it has been merged)

@playpaolo i think you can simply drag and drop the gif here

**Pull request merged**
