### PR TITLE
Pfem/materials file

### PR DESCRIPTION
**Pull request by jginternational**
Materials file written instead of mdpa properties

implements first point of #713 
implements KratosMultiphysics/Kratos/pull/6258

### CODE REVIEW

**Comment by MZecchetto** [comment]
Hi @jginternational ,
first comment. we need to add the following to the `solver_settings` in the `ProjectParameters.json`
`"material_import_settings"           : {
            "materials_filename" : "PFEMFluidMaterials.json"
        },`

Second comment. we need to remove the constitutive laws in the `PFEMFluidMaterials.json` as they are not supported by the PFEMFluidApp. I would comment the script instead of delete it, since it can be useful in the near future.

**Comment by MZecchetto** [comment]
Third comment. Is possible to have a property for each group of elements? In particular also for each rigid boundary group. In this case they are kept separated in the GiD post process. For the 2D example this means add to the PFEMFluidMaterials:

`{        "model_part_name" : "PfemFluidModelPart.Parts_Rigid_Walls",

        "properties_id"   : 2,

        "Material"        : {
            "Variables"        : {},
            "Tables"           : {}
        }
    }`

**Comment by jginternational** [comment]
@MZecchetto Points 1 and 2 are done. 
Point 3 is a bit difficult and I don't know if setting "empty properties" in the materials json is the proper way

**Comment by MZecchetto** [comment]
With these last two commits everything works fine. 
Adding "empty properties" works for the pfem app, also with the material.json. As far as I understood, the GiD post process uses the property Id to assign the elements to the different layers. Are there better ways to do so?

**Pull request merged**
