### PR TITLE
Hotfix fsi submodelparts

### PR DESCRIPTION
**Pull request by jginternational**
Implements #814

### CODE REVIEW

**Comment by jginternational** [comment]
@rubenzorrilla You can see that also python functions are fixed by using intervals

**Comment by jginternational** [comment]
MOK 3D still fails:

```
Traceback (most recent call last):
  File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 35, in <module>
    simulation.Run()
  File "E:\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 47, in Run
    self.Initialize()
  File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 16, in Initialize
    super().Initialize()
  File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_analysis.py", line 23, in Initialize
    self._GetSolver().PrepareModelPart()
  File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\partitioned_fsi_base_solver.py", line 128, in PrepareModelPart
    self._GetFSICouplingInterfaceStructure().GetInterfaceModelPart()
  File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 92, in GetInterfaceModelPart
    self._fsi_interface_model_part = self._create_fsi_interface_model_part()
  File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 321, in _create_fsi_interface_model_part
    self._get_partitioned_fsi_utilities().CreateCouplingSkin(
RuntimeError: Error: Invalid points number. Expected 3, given 4




in kratos/geometries/triangle_3d_3.h:242:Triangle3D3<class Node<3,class Dof > >::Triangle3D3
   kratos/conditions/mesh_condition.cpp:96:MeshCondition::Create
   kratos/sources/model_part.cpp:1489:ModelPart::CreateNewCondition
   kratos/sources/model_part.cpp:1460:ModelPart::CreateNewCondition

```
[mok3Dfails.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/6649846/mok3Dfails.gid.zip)

**Comment by rubenzorrilla** [comment]
> 
> 
> @rubenzorrilla You can see that also python functions are fixed by using intervals

I see, as a temporary solution I'm locally doing this. The point is that there is an ongoing PR that should make possible to keep the current syntax (this is why I wanted to keep them as they are).

**Comment by rubenzorrilla** [comment]
> 
> 
> MOK 3D still fails:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 35, in <module>
>     simulation.Run()
>   File "E:\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 47, in Run
>     self.Initialize()
>   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 16, in Initialize
>     super().Initialize()
>   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_analysis.py", line 23, in Initialize
>     self._GetSolver().PrepareModelPart()
>   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\partitioned_fsi_base_solver.py", line 128, in PrepareModelPart
>     self._GetFSICouplingInterfaceStructure().GetInterfaceModelPart()
>   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 92, in GetInterfaceModelPart
>     self._fsi_interface_model_part = self._create_fsi_interface_model_part()
>   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 321, in _create_fsi_interface_model_part
>     self._get_partitioned_fsi_utilities().CreateCouplingSkin(
> RuntimeError: Error: Invalid points number. Expected 3, given 4
> 
> 
> 
> 
> in kratos/geometries/triangle_3d_3.h:242:Triangle3D3<class Node<3,class Dof > >::Triangle3D3
>    kratos/conditions/mesh_condition.cpp:96:MeshCondition::Create
>    kratos/sources/model_part.cpp:1489:ModelPart::CreateNewCondition
>    kratos/sources/model_part.cpp:1460:ModelPart::CreateNewCondition
> ```
> 
> [mok3Dfails.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/6649846/mok3Dfails.gid.zip)

I think it is because you meshed the structure with hexas instead of using tetras. Could this be the reason?

**Comment by jginternational** [comment]
> > MOK 3D still fails:
> > ```
> > Traceback (most recent call last):
> >   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 35, in <module>
> >     simulation.Run()
> >   File "E:\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 47, in Run
> >     self.Initialize()
> >   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 16, in Initialize
> >     super().Initialize()
> >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_analysis.py", line 23, in Initialize
> >     self._GetSolver().PrepareModelPart()
> >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\partitioned_fsi_base_solver.py", line 128, in PrepareModelPart
> >     self._GetFSICouplingInterfaceStructure().GetInterfaceModelPart()
> >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 92, in GetInterfaceModelPart
> >     self._fsi_interface_model_part = self._create_fsi_interface_model_part()
> >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 321, in _create_fsi_interface_model_part
> >     self._get_partitioned_fsi_utilities().CreateCouplingSkin(
> > RuntimeError: Error: Invalid points number. Expected 3, given 4
> > 
> > 
> > 
> > 
> > in kratos/geometries/triangle_3d_3.h:242:Triangle3D3<class Node<3,class Dof > >::Triangle3D3
> >    kratos/conditions/mesh_condition.cpp:96:MeshCondition::Create
> >    kratos/sources/model_part.cpp:1489:ModelPart::CreateNewCondition
> >    kratos/sources/model_part.cpp:1460:ModelPart::CreateNewCondition
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [mok3Dfails.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/6649846/mok3Dfails.gid.zip)
> 
> I think it is because you meshed the structure with hexas instead of using tetras. Could this be the reason?

Yes but we are using that hexas since... 2017
https://github.com/KratosMultiphysics/GiDInterface/blob/790c0507c576424158fc06bb7adcddca8f810321/kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl#L167
Added in the commit https://github.com/KratosMultiphysics/GiDInterface/commit/cd34f608da309b4ea8bd4f444c3aaa4bfc368559

**Comment by rubenzorrilla** [comment]
> 
> 
> > > MOK 3D still fails:
> > > ```
> > > Traceback (most recent call last):
> > >   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 35, in <module>
> > >     simulation.Run()
> > >   File "E:\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 47, in Run
> > >     self.Initialize()
> > >   File "C:\Users\garat\Desktop\aaa.gid\MainKratos.py", line 16, in Initialize
> > >     super().Initialize()
> > >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_analysis.py", line 23, in Initialize
> > >     self._GetSolver().PrepareModelPart()
> > >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\partitioned_fsi_base_solver.py", line 128, in PrepareModelPart
> > >     self._GetFSICouplingInterfaceStructure().GetInterfaceModelPart()
> > >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 92, in GetInterfaceModelPart
> > >     self._fsi_interface_model_part = self._create_fsi_interface_model_part()
> > >   File "E:\Deploy_Kratos\KratosMultiphysics\FSIApplication\fsi_coupling_interface.py", line 321, in _create_fsi_interface_model_part
> > >     self._get_partitioned_fsi_utilities().CreateCouplingSkin(
> > > RuntimeError: Error: Invalid points number. Expected 3, given 4
> > > 
> > > 
> > > 
> > > 
> > > in kratos/geometries/triangle_3d_3.h:242:Triangle3D3<class Node<3,class Dof > >::Triangle3D3
> > >    kratos/conditions/mesh_condition.cpp:96:MeshCondition::Create
> > >    kratos/sources/model_part.cpp:1489:ModelPart::CreateNewCondition
> > >    kratos/sources/model_part.cpp:1460:ModelPart::CreateNewCondition
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [mok3Dfails.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/6649846/mok3Dfails.gid.zip)
> > 
> > 
> > I think it is because you meshed the structure with hexas instead of using tetras. Could this be the reason?
> 
> Yes but we are using that hexas since... 2017
> 
> https://github.com/KratosMultiphysics/GiDInterface/blob/790c0507c576424158fc06bb7adcddca8f810321/kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl#L167
> 
> Added in the commit [cd34f60](https://github.com/KratosMultiphysics/GiDInterface/commit/cd34f608da309b4ea8bd4f444c3aaa4bfc368559)

I know, but we improved the implementation (broking the hexas). Would you mind opening an issue so I can have a look?

**Pull request merged**
