### PR TITLE
Migrate structural

### PR DESCRIPTION
**Pull request by jginternational**
Another one I can not run @rubenzorrilla 

[structure_as_geometry.gid.zip](https://github.com/user-attachments/files/16284900/structure_as_geometry.gid.zip)

### CODE REVIEW

**Comment by jginternational** [comment]
Depends on #985

**Comment by rubenzorrilla** [comment]
[structure_as_geometry.gid.zip](https://github.com/user-attachments/files/16312209/structure_as_geometry.gid.zip)

To make it work, I added:
- properties 1 to the mdpa
- assigning the properties to the entire model part so the conditions also have properties (hacky, as I conditions should have different properties than the elements)

**Comment by rubenzorrilla** [comment]
[structure_as_geometry.gid.zip](https://github.com/user-attachments/files/16312315/structure_as_geometry.gid.zip)

I'd do something like this
- there are no properties in the mdpa
- we assign the "fake" 0 properties to the conditions in the  `StructuralMaterials.json` (we can hardcode this for the moment)

**Comment by rubenzorrilla** [comment]
Indeed, al these issues come from the fact that our `gid_output_process.py` maps our properties to output layers. Rather than adding fake properties to the materials json, I think we'd better amend the output stuff.

**Pull request merged**
