### PR TITLE
Updating structural mechanics solvers#159

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Dear all,

Finally we manage to keep all your changes except the "dynamic"/"static" field, which values are "Dynamic"/"Static" (the main reason is to keep the stable interface version until the released is packaged #159).

@loumalouomega is doing a PR in the StructuralMechanicsApplication to include such "Dynamic"/"Static"  modifications.

Hope this is ok for you.

### CODE REVIEW

**Comment by philbucher** [comment]
Hi Guys,
Thx for your effort!
@rubenzorrilla could you please also add the new elements that I described in issue #159 ?

@jginternational I see your point, but I also think that at some point we should stick to (our own) conventions. It is a developer verion

**Comment by philbucher** [comment]
Before I forget, should we change this after the release then?
Or are there too many dependencies somewhere else?

**Comment by rubenzorrilla** [comment]
@philbucher I can add the shells tomorrow morning. Regarding the beam and the truss elements, I don't know if the interface is already prepared for including them...

**Comment by philbucher** [comment]
@rubenzorrilla thx
there was a beam already, which has been replaced, so I guess the interface is there.

**Comment by rubenzorrilla** [comment]
Ok. Lets ping @jginternational for the beams issue.

**Comment by jginternational** [comment]
As far as I know there is a BeamElement in the interface, but we need to improve it (section type?, rotation angle from the local axis convention...)
@rubenzorrilla we can work on it tomorrow morning, because then I'll be out until next week

**Comment by philbucher** [comment]
@jginternational there is an old beam element, but it was removed from Kratos already.
@KlausBSautter is working on testing the local axis workflow you recently implemented.
However the truss elements you can add for sure, they don't need the local axis feature

**Pull request merged**
