### PR TITLE
More flushes at the beginning of the computation, to show the user that something is happening.

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
I'd consistently do the same in the other applications.

**Comment by maceligueta** [comment]
> I'd consistently do the same in the other applications.

Yes, I spoke to @jginternational on the phone that this PR could be useful to change all the main scripts. I said I would push the one I have already modified in my PC. Please do not merge until all of them are done.

**Comment by rubenzorrilla** [comment]
Cool! Thanks MA!

**Comment by maceligueta** [comment]
@jginternational , I updated some of the scripts. I could not test them all. Can you take a look at them?

**Comment by rubenzorrilla** [comment]
> @jginternational , I updated some of the scripts. I could not test them all. Can you take a look at them?

Shouldn't we make the same in all the applications? (some of them are missing e.g. `Structural`)

**Comment by maceligueta** [comment]
ping @jginternational . I changed many applications but I don't have a reliable way to test them all. Is there a way to check that I did not break anything?

**Comment by jginternational** [comment]
I have a test tool but it does not test this feature. We just check that the interface writes and that kratos reads and starts calculating

**Comment by maceligueta** [comment]
Well, if it starts calculating that would be a lot. I am actually worried about missing imports and syntax errors in the launcher Python script.

**Review by rubenzorrilla — APPROVED** [review]
I went through the changes and everything seems fine to me. Considering that there is no automatic mechanism to test this as well as that the eventual issues raising from these changes should be easy to track and fix I'd merge it.

**Comment by rubenzorrilla** [comment]
BTW, MA thanks for the clean up!

**Review by jginternational — APPROVED** [review]

**Comment by jginternational** [comment]
All testes passed after merging master into this branch -> 👍

**Pull request merged**
