### PR TITLE
Improve vectorial nodal displacement proposal null #428

### PR DESCRIPTION
**Pull request by jginternational**
Implements #428 
Let's see your impressions by checking some situations in the current GUI, and the equivalent in the new proposal:
### Old GUI
image
You can see that there is a lot of information in the screen. This will generate the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
}
```
### New proposal
image
It's a more compact solution (better for small screens) and simplifies the data input. Generates the following json:
```
{
        "constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
 }
```
As you can see, it's the same json as the old one

### Old GUI
image
This case generates the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto2",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [false,false,true],
                "value"           : [0.0,0.0,"(y/2)*t"],
                "interval"        : [0.0,"End"]
            }
}
```
And the problem here is that the X and Y axis are not set to null, and the json is still valid.

### New proposal
image
Again, you can see a compact design, that generates the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto2",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [false,false,true],
                "value"           : [null,null,"(2*z)+t"],
                "interval"        : [0.0,"End"]
            }
}
```
This way, X and Y displacement will be **NULL instead of 0.0**. If I want to set those components to 0.0, I'll need to create another assignation to the same group and select XY as Axis.
image

If you agree, I'll work on this solution and will be applied to all conditions that use the `assign_vector_variable_process` process 

My proposal to (and as a member of) @KratosMultiphysics/interface-committee 
Also ping @KratosMultiphysics/technical-committee

### CODE REVIEW

**Comment by jginternational** [comment]
@rubenzorrilla said in https://github.com/KratosMultiphysics/GiDInterface/issues/428#issuecomment-511878495

> From the description above I understand that it is possible to impose more than one direction at the same time only if the value is the same for all the constrained (or initialized) directions.
What I don't like so much is that it is needed to set multiple constraints if the value between the directions to be set is different. The point is that there is no unique manner...
Having said this, I'd be in favour of keeping `XYZ`, `X`, `Y` and `Z` and removing the "double" directions.

**Comment by jginternational** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by jginternational** [comment]
# Meeting 25/07/2019
Attendants: @RiccardoRossi @pooyan-dadvand  @roigcarlo  @rubenzorrilla  @jginternational 

After a short explanation of the pros/cons of this solution:
### pros
- More compact
### cons
- As @RiccardoRossi said, when applying different values in different axis in the same submodelpart, 2 different "vector processes are applied". 

## New proposal by @RiccardoRossi 
For each component `x, y, z` :
- A dropdown that allows the selection of the behaviour:
    - NotApplied: Will set value to `null `and imposed to `false`
    - AppliedByValue: Will set value to `user entry value` and imposed to `false`
    - AppliedByFunction: Will set value to `user entry function` and imposed to `false`
    - ImposedByValue: Will set value to `user entry value` and imposed to `true`
    - ImposedByFunction: Will set value to `user entry function` and imposed to `false`

A simple mockup:
image

As you can see: 
- X is set to value, so lets you insert a value
- Y is set to function, so lets you insert a function
- Z is set to Not apply, so doesn't let you insert anything else

The mockup here would write:

```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [false,true,false],
                "value"           : [0.0,"3t",null],
                "interval"        : [0.0,"End"]
            }
}
```

**Comment by rubenzorrilla** [comment]
@jginternational which is the status of this?

**Comment by jginternational** [comment]
GUI ready, 
image

Writing pending

**Comment by jginternational** [comment]
@rubenzorrilla you can try it.
The examples are still missing

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla you can try it.
> The examples are still missing

Which kind of examples you need?

**Comment by jginternational** [comment]
I meant the app examples (the buttons in the toolbar) are not updated yet

**Comment by jginternational** [comment]
READY TO MERGE !

**Pull request merged**
