### PR TITLE
[Fluid] Use GiDOutputProcess-Factory

### PR DESCRIPTION
**Pull request by philbucher**
fyi @KratosMultiphysics/fluid-dynamics 

Using the new factory of the GidOutputProcess to be more consistent with the other processes

see #453

### CODE REVIEW

**Comment by philbucher** [comment]
yep fully retrocompatible, same as for the processes

**Comment by philbucher** [comment]
you can checkout the code in the FluidAnalysis (the structural has the same) to see how the retrocompatibility works:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/fluid_dynamics_analysis.py#L74-L78

In fact this is like this for some months already, this PR updates it to the new format, which is possible since you added the factory to the `GiDOutputProcess`

**Comment by philbucher** [comment]
output before this PR:
~~~
"output_configuration"     : {
    "result_file_configuration" : {
        "gidpost_flags"       : {
            "GiDPostMode"           : "GiD_PostBinary",
            "WriteDeformedMeshFlag" : "WriteDeformed",
            "WriteConditionsFlag"   : "WriteConditions",
            "MultiFileFlag"         : "SingleFile"
        },
        "file_label"          : "step",
        "output_control_type" : "step",
        "output_frequency"    : 1,
        "body_output"         : true,
        "node_output"         : false,
        "skin_output"         : false,
        "plane_output"        : [],
        "nodal_results"       : ["DISPLACEMENT","REACTION","ROTATION"],
        "gauss_point_results" : []
    },
    "point_data_configuration"  : []
}
~~~

After this PR:
~~~
"output_processes"         : {
    "gid_output" : [{
        "python_module" : "gid_output_process",
        "kratos_module" : "KratosMultiphysics",
        "process_name"  : "GiDOutputProcess",
        "help"          : "This process writes postprocessing files for GiD",
        "Parameters"    : {
            "model_part_name"        : "Structure.computing_domain",
            "output_name"            : "Structure",
            "postprocess_parameters" : {
                "result_file_configuration" : {
                    "gidpost_flags"       : {
                        "GiDPostMode"           : "GiD_PostBinary",
                        "WriteDeformedMeshFlag" : "WriteDeformed",
                        "WriteConditionsFlag"   : "WriteConditions",
                        "MultiFileFlag"         : "SingleFile"
                    },
                    "file_label"          : "step",
                    "output_control_type" : "step",
                    "output_frequency"    : 1,
                    "body_output"         : true,
                    "node_output"         : false,
                    "skin_output"         : false,
                    "plane_output"        : [],
                    "nodal_results"       : ["DISPLACEMENT","REACTION","ROTATION"],
                    "gauss_point_results" : []
                },
                "point_data_configuration"  : []
            }
        }
    }]
}
~~~


See the [AnalysisStage-Wiki](https://github.com/KratosMultiphysics/Kratos/wiki/Common-Python-Interface-of-Applications-for-Users#analysisstage-usage)

**Comment by loumalouomega** [comment]
I like it

**Comment by RiccardoRossi** [comment]
just one petition: put an entry in the wiki with the new format, and in the deprecation warning refer to this issue

**Comment by philbucher** [comment]
@RiccardoRossi it is described in the Wiki for a long time already

**Comment by philbucher** [comment]
@RiccardoRossi see https://github.com/KratosMultiphysics/Kratos/pull/2851

**Comment by rubenzorrilla** [comment]
@jginternational and for ConvectionDiffusion as well

**Pull request merged**
