### PR TITLE
Enhacement structural contact #298

### PR DESCRIPTION
**Pull request by jginternational**
Check it please

### CODE REVIEW

**Comment by loumalouomega** [comment]
Does not work:
imagen
And can you change the name of master and slave to the inverse one? (what you call master call slave and vice versa)

**Comment by jginternational** [comment]
That was meant to be run in GiD 14, 

it should work now

**Comment by loumalouomega** [comment]
Can you change the master/slave names ?

**Comment by loumalouomega** [comment]
Thanks

**Comment by loumalouomega** [comment]
Should write:

~~~json
"contact_settings"                   : {
            "mortar_type" : "ALMContactFrictionlessComponents"
        }
~~~
 
instead of : 

~~~json
"contact_settings"                   : {
            "mortar_type" : "ALMContactFrictionless"
        }
~~~

**Comment by loumalouomega** [comment]
The contact model part name can be refined now is:

    CONTACT__HIDDEN_CONTACT_GROUP_

**Pull request merged**
