### PR TITLE
Hide end calculation window

### PR DESCRIPTION
**Pull request by jginternational**
This PR allows the apps to remove the windows after the calculation process
And sets the DEM app as example:

Caution:
- Works with 15.1.0d and later
- Also removes the error window if the calculation process went wrong.

@maceligueta @farrufat-cimne

### CODE REVIEW

**Comment by maceligueta** [comment]
Hi @jginternational  and @farrufat-cimne . We did not need this for the DEM. It was intended for an independent problemtype.

I am OK with it if it's useful in the future or for other apps, however, as I said, **we do not currently need this for the DEM**.

**Comment by jginternational** [comment]
Ok, it is commented for the DEM. It was just an example for @farrufat-cimne .

As you can see, once implemented the event GiD_Event_AfterRunCalculation , if you don't want that window, just return -cancel-

**Comment by maceligueta** [comment]
Great then!

**Comment by farrufat-cimne** [comment]
Thx Javi

**Pull request closed without merging**
