### PR TITLE
[WIP] Make vtk-output optional

### PR DESCRIPTION
**Pull request by philbucher**
I started making the vtk-output optional
Screenshot from 2019-04-25 10-16-29

This is implemented in a generic way such that it can be used from any app

@jginternational I started with this but then I got stuck bcs I am not familiar with the tcl too much and don't want to mess up your stuff

I would like to hear others opinions on this (how it looks visually) then we can think abt the details / which options to expose

### CODE REVIEW

**Comment by jginternational** [comment]
👏 Nice!

Yesterday morning I was about to write you for this issue, adding the vtk options to the gui

Let me finish something first and then I'll help you with this.

**Comment by adityaghantasala** [comment]
This is very convenient. Just a small comment there could be a drop down option and then same (almost) options for each o/p format.

**Comment by loumalouomega** [comment]
Fixes https://github.com/KratosMultiphysics/Kratos/issues/4483

**Comment by philbucher** [comment]
@jginternational please let me know when it is ready for being tested
Thanks for your help

**Comment by jginternational** [comment]
I's almost ready. I'm changing some examples that modify the default value of some output properties, but you can try it @philbucher

**Comment by jginternational** [comment]
@philbucher I think it's over. You can test it!

**Comment by philbucher** [comment]
Hi @jginternational 
Thanks, I have the following comments:
- Can you please also make `output_control_type` and `output_frequency` available, same as for gid?
- No variables are written for the vtk, it should be the same as for gid

**Comment by philbucher** [comment]
I made a minor change related to GaussPoint results, but other than that it works nicely, thx

Only thing left is that it displays the "File Label", which is not used by the vtk-output, could you please remove it?

**Comment by jginternational** [comment]
@philbucher done!

**Comment by philbucher** [comment]
now it works perfectly, thanks @jginternational !

Feel free to merge this

**Pull request merged**
